web-application/UniDelWebApplication/WebApplication2/Controllers/FleetManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using UniDelWebApplication.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace UniDelWebApplication.Controllers
{

    public class FleetManagementController : Controller
    {
        private List<Vehicle> veh = new List<Vehicle>(){
                new Vehicle() { VehicleID = 0, VehicleMake = "A", VehicleModel = "Z", VehicleVIN = "I", VehicleMileage = 20, VehicleLicensePlate = "E", VehicleLicenseDiskExpiry = new DateTime(2033, 12, 25, 10, 30, 50), VehicleLastService = new DateTime(2019, 10, 25, 10, 30, 50), VehicleNextMileageService = 30, VehicleNextDateService = new DateTime(2020, 10, 25, 10, 30, 50) },
                new Vehicle() { VehicleID = 1, VehicleMake = "B", VehicleModel = "Y", VehicleVIN = "F", VehicleMileage = 12, VehicleLicensePlate = "E", VehicleLicenseDiskExpiry =new DateTime(2023, 12, 25, 10, 30, 50), VehicleLastService = new DateTime(2019, 10, 25, 10, 35, 50), VehicleNextMileageService = 30, VehicleNextDateService = new DateTime(2020, 10, 25, 10, 30, 50) },
                new Vehicle() { VehicleID = 2, VehicleMake = "C", VehicleModel = "X", VehicleVIN = "J", VehicleMileage = 23, VehicleLicensePlate = "E", VehicleLicenseDiskExpiry = new DateTime(2035, 12, 25, 10, 30, 50), VehicleLastService = new DateTime(2019, 10, 25, 10, 40, 50), VehicleNextMileageService = 30, VehicleNextDateService = new DateTime(2020, 10, 25, 10, 30, 50) },
                new Vehicle() { VehicleID = 3, VehicleMake = "D", VehicleModel = "W", VehicleVIN = "G", VehicleMileage = 10, VehicleLicensePlate = "E", VehicleLicenseDiskExpiry = new DateTime(2025, 12, 25, 10, 30, 50), VehicleLastService = new DateTime(2019, 10, 25, 10, 50, 50), VehicleNextMileageService = 30, VehicleNextDateService = new DateTime(2020, 10, 25, 10, 30, 50) },
                new Vehicle() { VehicleID = 4, VehicleMake = "E", VehicleModel = "V", VehicleVIN = "H", VehicleMileage = 26, VehicleLicensePlate = "E", VehicleLicenseDiskExpiry = new DateTime(2030, 12, 25, 10, 30, 50), VehicleLastService = new DateTime(2019, 10, 25, 11, 30, 50), VehicleNextMileageService = 30, VehicleNextDateService = new DateTime(2020, 10, 25, 10, 30, 50) }
        };

        // GET: /<controller>/
        public IActionResult Index(String sortV,String search)
        {
            List<Vehicle> v = new List<Vehicle>();
            //veh[0].VehicleMake=search;
            if (search==null)
                v = new List<Vehicle>(veh);
            else
            {
                foreach(var ve in veh)
                {
                    if (ve.VehicleVIN.Contains(search))
                        v.Add(ve);
                }
            }
            if (sortV=="vID")
                v = v.OrderBy(order => order.VehicleID).ToList();
            else if (sortV == "vMake")
                v = v.OrderBy(order => order.VehicleMake).ToList();
            else if (sortV == "vModel")
                v = v.OrderBy(order => order.VehicleModel).ToList();
            else if (sortV == "vVIN")
                v = v.OrderBy(order => order.VehicleVIN).ToList();
            else if (sortV == "vMileage")
                v = v.OrderBy(order => order.VehicleMileage).ToList();
            else if (sortV == "vLicensePlate")
                v = v.OrderBy(order => order.VehicleLicensePlate).ToList();
            else if (sortV == "vLicenseDiskExpiry")
                v = v.OrderBy(order => order.VehicleMileage).ToList();
            else if (sortV == "vLastService")
                v = v.OrderBy(order => order.VehicleLicenseDiskExpiry).ToList();
            else if (sortV == "vNextMileageService")
                v = v.OrderBy(order => order.VehicleNextMileageService).ToList();
            else if (sortV == "vNextDateService")
                v = v.OrderBy(order => order.VehicleNextDateService).ToList();
            return View(v);
        }

        public IActionResult AddVehicle()
        {
            return View();
        }

        public IActionResult Add(String vMake, String vModel,String vVIN, int vMileage, String vLicensePlate, DateTime vLicenseDiskExpiry, DateTime vLastService, int vNextMileageService, DateTime vNextDateService)
        {
            List<Vehicle> v = new List<Vehicle>();
            veh.Add(new Vehicle() { VehicleID = veh.Count(), VehicleMake = vMake, VehicleModel = vModel, VehicleVIN = vVIN, VehicleMileage = vMileage, VehicleLicensePlate = vLicensePlate, VehicleLicenseDiskExpiry = vLicenseDiskExpiry, VehicleLastService = vLastService, VehicleNextMileageService = vNextMileageService, VehicleNextDateService = vNextDateService });
            //Index(null,null);
            return View(veh);
        }

        public IActionResult CaptureService()
        {
            return View(veh);
        }

        public IActionResult Capture()
        {
            return View(veh);
        }

        public IActionResult RenewLicenseDisk()
        {
            return View();
        }

        public IActionResult Edit()
        {
            //page to edit any other vehicle details
            return View();
        }

        public IActionResult Delete()
        {
            //code to remove vehicle from system



            //redirect back to index page after deleting vehicle
            return new RedirectToPageResult("Index");
        }
    }
}

web-application/UniDelWebApplication/WebApplication2/Views/FleetManagement/Add.cshtml
@{
    ViewData["Title"] = "Add";
}

<div class="text-center">
    <h1 class="display-4">Fleet Management</h1>
</div>

@Html.ActionLink("Fleet Management", "Index", "FleetManagement")


<table border="1" cellpadding="11">
    <tr>
        <th>ID</th>
        <th>Make</th>
        <th>Model</th>
        <th>VIN</th>
        <th>Mileage</th>
        <th>License Plate</th>
        <th>License Disk Expiry</th>
        <th>Last Service</th>
        <th>Next Mileage Service</th>
        <th>Next Date Service</th>
    </tr>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.VehicleID</td>
                <td>@item.VehicleMake</td>
                <td>@item.VehicleModel</td>
                <td>@item.VehicleVIN</td>
                <td>@item.VehicleMileage</td>
                <td>@item.VehicleLicensePlate</td>
                <td>@item.VehicleLicenseDiskExpiry</td>
                <td>@item.VehicleLastService</td>
                <td>@item.VehicleNextMileageService</td>
                <td>@item.VehicleNextDateService</td>
            </tr>
        }
    </tbody>
</table>
</div>

web-application/UniDelWebApplication/WebApplication2/Views/FleetManagement/AddVehicle.cshtml
@{
    ViewData["Title"] = "Add Vehicle";
}

<div class="text-center">
    <h1 class="display-4">Add Vehicle</h1>
</div>

@using (Html.BeginForm("Add", "FleetManagement", FormMethod.Post))
{
    <label for="vMake">Make:</label>
    <input type="text" id="vMake" name="vMake" placeholder="SUBARU"><br>
    <label for="vModel">Model:</label>
    <input type="text" id="vModel" name="vModel" placeholder="Legacy"><br>
    <label for="vVIN">VIN:</label>
    <input type="text" id="vVIN" name="vVIN" placeholder="4S3BMHB68B3286050"><br>
    <label for="vMileage">Mileage:</label>
    <input type="number" id="vMileage" name="vMileage" placeholder="100 000"><br>
    <label for="vLicensePlate">License Plate:</label>
    <input type="text" id="vLicensePlate" name="vLicensePlate" placeholder="AB 45 XY GP"><br>
    <label for="vLicenseDiskExpiry">License Disk Expiry:</label>
    <input type="date" id="vLicenseDiskExpiry" name="vLicenseDiskExpiry"><br>
    <label for="vLastService">Last Service:</label>
    <input type="date" id="vLastService" name="vLastService"><br>
    <label for="vNextMileageService">Model:</label>
    <input type="number" id="vNextMileageService" name="vNextMileageService" placeholder="300 000"><br>
    <label for="vNextDateService">Next Date Service:</label>
    <input type="date" id="vNextDateService" name="vNextDateService"><br>
    <input type="submit" value="Add Vehicle">
}

web-application/UniDelWebApplication/WebApplication2/Views/FleetManagement/Capture.cshtml
@{
    ViewData["Title"] = "Capture Service";
}

<div class="text-center">
    <h1 class="display-4">Captured</h1>
    <p></p>
</div>

web-application/UniDelWebApplication/WebApplication2/Views/FleetManagement/CaptureService.cshtml
@{
    ViewData["Title"] = "Capture Service";
}

@using UniDelWebApplication.Models
@model Vehicle

<h1>Capture a Service</h1>

<!-- have to add mock data into database then will display the model Vehicle info-->

<form>
    <div class="form-group row">
        <label for="vehicle_mileage" class="col-sm-2 col-form-label">Vehicle mileage</label>
        <div class="col-sm-10">
            <input type="text" readonly class="form-control-plaintext" id="vehicle_mileage" value=@Html.DisplayFor(m => m.VehicleMileage)>
        </div>
    </div>
    <div class="form-group row">
        <label for="vehicle_next_mileage_service" class="col-sm-2 col-form-label">Vehicle next mileage service</label>
        <div class="col-sm-10">
            <input type="text" readonly class="form-control-plaintext" id="vehicle_next_mileage_service" value=@Html.DisplayFor(m => m.VehicleNextMileageService)>
        </div>
    </div>
    <div class="form-group row">
        <label for="vehicle_last_service" class="col-sm-2 col-form-label">Vehicle last service</label>
        <div class="col-sm-10">
            <input type="text" readonly class="form-control-plaintext" id="vehicle_last_service" value=@Html.DisplayFor(m => m.VehicleLastService)>
        </div>
    </div>
    <div class="form-group row">
        <label for="vehicle_next_service" class="col-sm-2 col-form-label">Vehicle next service</label>
        <div class="col-sm-10">
            <input type="text" readonly class="form-control-plaintext" id="vehicleMileage" value=@Html.DisplayFor(m => m.VehicleNextDateService)>
        </div>
    </div>

    <!--if a service was done today the box will be checked and the inputs above will turn off of read only - press submit to save changes-->
    <div class="form-group form-check">
        <input type="checkbox" class="form-check-input" id="checkbox">
        <label class="form-check-label" for="checkbox">Was a service done today?</label>
    </div>
    <div>
        <button type="button" class="btn btn-light">Submit</button>
    </div>
</form>

web-application/UniDelWebApplication/WebApplication2/Views/FleetManagement/Edit.cshtml
@{
    ViewData["Title"] = "Edit Information";
}


@using UniDelWebApplication.Models
@model Vehicle

<h1>Vehicle Information</h1>

<form>
    <div class="form-group row">
        <label for="vehicle_id" class="col-sm-2 col-form-label">Vehicle ID</label>
        <div class="col-sm-10">
            <input type="text" readonly class="form-control-plaintext" id="vehicle_id" value=@Html.DisplayFor(m => m.VehicleID)>
        </div>
    </div>
    <div class="form-group row">
        <label for="vehicle_make" class="col-sm-2 col-form-label">Vehicle make</label>
        <div class="col-sm-10">
            <input type="text" readonly class="form-control-plaintext" id="vehicle_make" value=@Html.DisplayFor(m => m.VehicleMake)>
        </div>
    </div>
    <div class="form-group row">
        <label for="vehicle_model" class="col-sm-2 col-form-label">Vehicle model</label>
        <div class="col-sm-10">
            <input type="text" readonly class="form-control-plaintext" id="vehicle_model" value=@Html.DisplayFor(m => m.VehicleModel)>
        </div>
    </div>
    <div class="form-group row">
        <label for="vehicle_license_plate" class="col-sm-2 col-form-label">Vehicle license plate</label>
        <div class="col-sm-10">
            <input type="text" readonly class="form-control-plaintext" id="vehicle_license_plate" value=@Html.DisplayFor(m => m.VehicleLicensePlate)>
        </div>
    </div>
    <div class="form-group row">
        <label for="vehicle_vin" class="col-sm-2 col-form-label">Vehicle VIN</label>
        <div class="col-sm-10">
            <input type="text" readonly class="form-control-plaintext" id="vehicle_vin" value=@Html.DisplayFor(m => m.VehicleVIN)>
        </div>
    </div>
    <div class="form-group row">
        <label for="vehicle_mileage" class="col-sm-2 col-form-label">Vehicle mileage</label>
        <div class="col-sm-10">
            <input type="text" readonly class="form-control-plaintext" id="vehicleMileage" value=@Html.DisplayFor(m => m.VehicleMileage)>
        </div>
    </div>
    <div class="form-group row">
        <label for="vehicle_nextMileage" class="col-sm-2 col-form-label">Vehicle next mileageservice</label>
        <div class="col-sm-10">
            <input type="text" readonly class="form-control-plaintext" id="vehicle_nextMileage" value=@Html.DisplayFor(m => m.VehicleNextMileageService)>
        </div>
    </div>
    <div class="form-group row">
        <label for="vehicle_licenseExpiry" class="col-sm-2 col-form-label">Vehicle license disk expiry</label>
        <div class="col-sm-10">
            <input type="text" readonly class="form-control-plaintext" id="vehicle_licenseExpiry" value=@Html.DisplayFor(m => m.VehicleLicenseDiskExpiry)>
        </div>
    </div>
    <div class="form-group row">
        <label for="vehicle_lastService" class="col-sm-2 col-form-label">Vehicle last service</label>
        <div class="col-sm-10">
            <input type="text" readonly class="form-control-plaintext" id="vehicle_lastService" value=@Html.DisplayFor(m => m.VehicleLastService)>
        </div>
    </div>
    <div class="form-group row">
        <label for="vehicle_next_service" class="col-sm-2 col-form-label">Vehicle next service</label>
        <div class="col-sm-10">
            <input type="text" readonly class="form-control-plaintext" id="vehicle_nextService" value=@Html.DisplayFor(m => m.VehicleNextDateService)>
        </div>
    </div>

    <div class="form-group form-check">
        <input type="checkbox" class="form-check-input" id="checkbox">
        <label class="form-check-label" for="checkbox">Edit vehicle info</label>
    </div>
    <!--uf checkbox is checked then inputs will turn off of read only and can change values-->
    <div>
        <button type="button" class="btn btn-light">Submit</button>
    </div>
</form>

web-application/UniDelWebApplication/WebApplication2/Views/FleetManagement/Index.cshtml
@{
    ViewData["Title"] = "Fleet Management";
}

<div class="text-center">
    <h1 class="display-4">Fleet Management</h1>
</div>

<h2>Vehicles</h2>
@Html.ActionLink("Add", "AddVehicle", "FleetManagement")<br>
@Html.ActionLink("Capture Service", "CaptureService", "FleetManagement")<br>
@Html.ActionLink("Renew License Disk", "RenewLicenseDisk", "FleetManagement")<br>
@Html.ActionLink("Edit", "Edit", "FleetManagement")<br>

@using (Html.BeginForm("Index", "FleetManagement", FormMethod.Post))
{
    <input type="text" name="search" placeholder="Search..">
    <input type="submit" value="Search">
}


@using (Html.BeginForm("Index", "FleetManagement", FormMethod.Post))
{
    <label for="sortV">Sort by:</label>
    <select name="sortV" id="sortV">
        <option value="vId">ID</option>
        <option value="vMake">Make</option>
        <option value="vModel">Model</option>
        <option value="vVIN">VIN</option>
        <option value="vMileage">Mileage</option>
        <option value="vLicensePlate">License Plate</option>
        <option value="vLicenseDiskExpiry">License Disk Expiry</option>
        <option value="vLastService">Last Service</option>
        <option value="vNextMileageService">Next Mileage Service</option>
        <option value="vNextDateService">Next Date Service</option>
    </select>
    <input type="submit" value="Sort">
}

<div style="overflow-x:auto;">
    <table border="1" cellpadding="11">
        <tr>
            <th>ID</th>
            <th>Make</th>
            <th>Model</th>
            <th>VIN</th>
            <th>Mileage</th>
            <th>License Plate</th>
            <th>License Disk Expiry</th>
            <th>Last Service</th>
            <th>Next Mileage Service</th>
            <th>Next Date Service</th>
        </tr>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.VehicleID</td>
                    <td>@item.VehicleMake</td>
                    <td>@item.VehicleModel</td>
                    <td>@item.VehicleVIN</td>
                    <td>@item.VehicleMileage</td>
                    <td>@item.VehicleLicensePlate</td>
                    <td>@item.VehicleLicenseDiskExpiry</td>
                    <td>@item.VehicleLastService</td>
                    <td>@item.VehicleNextMileageService</td>
                    <td>@item.VehicleNextDateService</td>
                </tr>
            }
        </tbody>
    </table>
</div>

web-application/UniDelWebApplication/WebApplication2/Views/FleetManagement/RenewLicenseDisk.cshtml
@{
    ViewData["Title"] = "License Disk Renewal";
}

@using UniDelWebApplication.Models
@model Vehicle

<h1>License Disk Renewal</h1>

<!-- have to add mock data into database then will display the model Vehicle info-->

<form>
    <div class="form-group row">
        <label for="license_disk_expiry" class="col-sm-2 col-form-label">License Disk Expiry Date</label>
        <div class="col-sm-10">
            <input type="text" readonly class="form-control-plaintext" id="license_disk_expiry" value=@Html.DisplayFor(m => m.VehicleLicenseDiskExpiry)>
        </div>
    </div>
    <div class="form-group form-check">
        <input type="checkbox" class="form-check-input" id="checkbox">
        <label class="form-check-label" for="checkbox">Renew License Disk</label>
    </div>
    <div class="input-group input-group-sm mb-3">
        <span class="input-group-text" id="inputGroup-sizing-sm">New License Expiry Date</span>
        <input type="date" class="form-control" aria-label="New License Expiry Date" aria-describedby="inputGroup-sizing-sm">
    </div>
    <div>
        <button type="button" class="btn btn-light">Submit</button>
    </div>

</form>